export const eventCategories = [
  'Music',
  'Comedy',
  'Sports',
  'Theater',
  'Dance',
  'Art',
  'Food',
  'Technology',
  'Business',
  'Health',
  'Education',
  'Kids',
  'Fashion',
  'Photography',
  'Literature',
  'Film',
  'Gaming',
  'Fitness',
  'Travel',
  'Workshop'
];

const sampleEvents = [
  {
    id: 1,
    title: 'Return Of The Dragon | Bengaluru',
    date: 'Sat, 26 Jul | 6 PM onwards',
    venue: 'Thiruvidanthai, ECR, Chennai',
    status: 'Available',
    categories: ["Music"],
    image: require('../../assets/images/hip.jpg'),
    description: 'After 3 long years, Anirudh Ravichander returns to his hometown for a thunderous comeback like never before! The Hukum World Tour arrives in Chennai with all guns blazing — a grand spectacle...',
    language: 'Tamil',
    duration: '4 Hours',
    ageLimit: '5 years & above',
    entryAllowed: 'All ages',
    layout: 'Outdoor',
    seating: 'Seated & Standing',
    kidFriendly: 'Yes',
    petFriendly: 'No',
    artist: {
      name: 'Anirudh Ravichander',
      category: 'Tamil, Music',
      songs: [
        'Chikitu (From "Coolie")',
        'Chaleya (From "Jawan")',
        'Chuttamalle (From "Devara Part 1")',
        'Pathikichu (From "Vidaa Muyarchi")',
        'Hukum – Thalaivar Alappara',
      ],
    },
    gallery: [
      require('../../assets/images/concept1.jpg'),
      require('../../assets/images/concept2.jpg'),
      require('../../assets/images/concept3.jpg'),
      require('../../assets/images/concept4.jpg'),
    ],
    prohibited: [
      'Outside Food & Beverage',
      'Alcohol',
      'Metal Container',
      'Glass containers',
      'Flammable Materials',
      'Lighter and Matchbox',
      'Aerosols/Deodorants',
      'Laser pointer/flashlight',
      'Drones',
      'Professional Cameras',
    ],
  },
  {
    id: 2,
    title: 'Hukum World Tour | Chennai',
    date: 'Sat, 26 Jul | 6 PM onwards',
    venue: 'Thiruvidanthai, ECR, Chennai',
    status: 'Available',
    categories: ["Music"],
    image: require('../../assets/images/ani.jpg'),
    description: 'After 3 long years, Anirudh Ravichander returns to his hometown for a thunderous comeback like never before! The Hukum World Tour arrives in Chennai with all guns blazing — a grand spectacle...',
    language: 'Tamil',
    duration: '4 Hours',
    ageLimit: '5 years & above',
    entryAllowed: 'All ages',
    layout: 'Outdoor',
    seating: 'Seated & Standing',
    kidFriendly: 'Yes',
    petFriendly: 'No',
    artist: {
      name: 'Anirudh Ravichander',
      category: 'Tamil, Music',
      songs: [
        'Chikitu (From "Coolie")',
        'Chaleya (From "Jawan")',
        'Chuttamalle (From "Devara Part 1")',
        'Pathikichu (From "Vidaa Muyarchi")',
        'Hukum – Thalaivar Alappara',
      ],
    },
    gallery: [
      require('../../assets/images/concept1.jpg'),
      require('../../assets/images/concept1.jpg'),
      require('../../assets/images/concept1.jpg'),
      require('../../assets/images/concept1.jpg'),
    ],
    prohibited: [
      'Outside Food & Beverage',
      'Alcohol',
      'Metal Container',
      'Glass containers',
      'Flammable Materials',
      'Lighter and Matchbox',
      'Aerosols/Deodorants',
      'Laser pointer/flashlight',
      'Drones',
      'Professional Cameras',
    ],
  },
  {
    id: 3,
    title: 'A.R Rahman | Hyderabad',
    date: 'Sat, 26 Jul | 6 PM onwards',
    venue: 'Thiruvidanthai, ECR, Chennai',
    status: 'Available',
    categories: ["Music"],
    image: require('../../assets/images/ar.jpg'),
    description: 'After 3 long years, Anirudh Ravichander returns to his hometown for a thunderous comeback like never before! The Hukum World Tour arrives in Chennai with all guns blazing — a grand spectacle...',
    language: 'Tamil',
    duration: '4 Hours',
    ageLimit: '5 years & above',
    entryAllowed: 'All ages',
    layout: 'Outdoor',
    seating: 'Seated & Standing',
    kidFriendly: 'Yes',
    petFriendly: 'No',
    artist: {
      name: 'Anirudh Ravichander',
      category: 'Tamil, Music',
      songs: [
        'Chikitu (From "Coolie")',
        'Chaleya (From "Jawan")',
        'Chuttamalle (From "Devara Part 1")',
        'Pathikichu (From "Vidaa Muyarchi")',
        'Hukum – Thalaivar Alappara',
      ],
    },
    gallery: [
      require('../../assets/images/concept1.jpg'),
      require('../../assets/images/concept1.jpg'),
      require('../../assets/images/concept1.jpg'),
      require('../../assets/images/concept1.jpg'),
    ],
    prohibited: [
      'Outside Food & Beverage',
      'Alcohol',
      'Metal Container',
      'Glass containers',
      'Flammable Materials',
      'Lighter and Matchbox',
      'Aerosols/Deodorants',
      'Laser pointer/flashlight',
      'Drones',
      'Professional Cameras',
    ],
  },
  {
    id: 4,
    title: 'Return Of The Dragon | Bengaluru',
    date: 'Sat, 26 Jul | 6 PM onwards',
    venue: 'Thiruvidanthai, ECR, Chennai',
    status: 'Available',
    categories: ["Music"],
    image: require('../../assets/images/hip.jpg'),
    description: 'After 3 long years, Anirudh Ravichander returns to his hometown for a thunderous comeback like never before! The Hukum World Tour arrives in Chennai with all guns blazing — a grand spectacle...',
    language: 'Tamil',
    duration: '4 Hours',
    ageLimit: '5 years & above',
    entryAllowed: 'All ages',
    layout: 'Outdoor',
    seating: 'Seated & Standing',
    kidFriendly: 'Yes',
    petFriendly: 'No',
    artist: {
      name: 'Anirudh Ravichander',
      category: 'Tamil, Music',
      songs: [
        'Chikitu (From "Coolie")',
        'Chaleya (From "Jawan")',
        'Chuttamalle (From "Devara Part 1")',
        'Pathikichu (From "Vidaa Muyarchi")',
        'Hukum – Thalaivar Alappara',
      ],
    },
    gallery: [
      require('../../assets/images/concept1.jpg'),
      require('../../assets/images/concept1.jpg'),
      require('../../assets/images/concept1.jpg'),
      require('../../assets/images/concept1.jpg'),
    ],
    prohibited: [
      'Outside Food & Beverage',
      'Alcohol',
      'Metal Container',
      'Glass containers',
      'Flammable Materials',
      'Lighter and Matchbox',
      'Aerosols/Deodorants',
      'Laser pointer/flashlight',
      'Drones',
      'Professional Cameras',
    ], 
  },
  // Add more events as needed
];

export default sampleEvents;