const events = [
  {
    id: 1,
    image: require('../../assets/images/sam.jpg'),
    title: 'Hiphop Tamizha - Live In Concert',
    date: '23 Aug, 6:30PM',
    venue: 'NICE Grounds, Bengaluru',
    price: '₹999 onwards',
  },
  {
    id: 2,
    image: require('../../assets/images/won.jpg'),
    title: 'Ashwin Srikumar Standup Show',
    date: '24 Aug, 7:00PM',
    venue: 'Phoenix Arena, Hyderabad',
    price: '₹799 onwards',
  },
  {
    id: 3,
    image: require('../../assets/images/ani_p.jpg'),
    title: 'The Great Art Expo',
    date: '25 Aug, 10:00AM',
    venue: 'Kala Academy, Goa',
    price: '₹250 onwards',
  },
  {
    id: 4,
    image: require('../../assets/images/ar_p.jpg'),
    title: 'Food Carnival – Taste the World',
    date: '26 Aug, 1:00PM',
    venue: 'Nehru Grounds, Delhi',
    price: '₹100 onwards',
  },
  {
    id: 5,
    image: require('../../assets/images/sam.jpg'),
    title: 'Live Jazz Evening by Blue Notes',
    date: '26 Aug, 6:00PM',
    venue: 'Jazz Yard, Mumbai',
    price: '₹599 onwards',
  },
  {
    id: 6,
    image: require('../../assets/images/hip_p.jpg'),
    title: 'Workshop: Learn Digital Illustration',
    date: '27 Aug, 2:00PM',
    venue: 'CreativeHub, Bengaluru',
    price: '₹850 onwards',
  },
  {
    id: 7,
    image: require('../../assets/images/won.jpg'),
    title: 'Kids Science Fair 2025',
    date: '28 Aug, 9:00AM',
    venue: 'Birla Science Museum, Hyderabad',
    price: '₹150 onwards',
  },
  {
    id: 8,
    image: require('../../assets/images/sam.jpg'),
    title: 'Photography Walk – Capture Chennai',
    date: '29 Aug, 5:30AM',
    venue: 'Marina Beach, Chennai',
    price: '₹300 onwards',
  },
  {
    id: 9,
    image: require('../../assets/images/hip_p.jpg'),
    title: 'Standup Night – Open Mic Special',
    date: '30 Aug, 8:00PM',
    venue: 'LaughOut Club, Pune',
    price: '₹200 onwards',
  },
  {
    id: 10,
    image: require('../../assets/images/ar_p.jpg'),
    title: 'Indie Film Screening – Short Films Fest',
    date: '31 Aug, 7:00PM',
    venue: 'Alliance Française, Delhi',
    price: 'Free Entry',
  },
  {
    id: 11,
    image: require('../../assets/images/ani_p.jpg'),
    title: 'Bangalore Coding Hackathon 2025',
    date: '1 Sept, 9:00AM',
    venue: 'Tech Hub, Bengaluru',
    price: '₹299 onwards',
  },
  {
    id: 12,
    image: require('../../assets/images/sam.jpg'),
    title: 'Dance Night – Salsa and More',
    date: '2 Sept, 7:00PM',
    venue: 'Club Nova, Pune',
    price: '₹450 onwards',
  },
];

export default events;